app = "Version-2" 
primary_region = "ash"

[build]
dockerfile = "Dockerfile"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  NODE_ENV = "production"
  NEXTAUTH_SECRET = "FlyV1 fm2_lJPECAAAAAAAC07NxBCSL6MvgoMmWRD0omfNcPbhwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOABTLGR8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDwQbNQ9u8ESLdqCHa51BcOGYJ24qhHcJPqYbSZnsi3qvJ+NXMLcmkPobrY/af+r9izxSBRzf2EVadjd93bETvHidoVvJsmW4y5UiWy6UHhQ+jqUcivQJXdJEtQ5TJrdNYlOUd8zQHlyApyTrKtF/8m+KSMi+XJr0SbxisaJtvHIGhWOYJTn+e+WxgLmZw2SlAORgc4AtYKCHwWRgqdidWlsZGVyH6J3Zx8BxCDz3F3J+m1hROAz+mf+1xN5qrf8pH0agwYMAAvk6LTlkA==,fm2_lJPETvHidoVvJsmW4y5UiWy6UHhQ+jqUcivQJXdJEtQ5TJrdNYlOUd8zQHlyApyTrKtF/8m+KSMi+XJr0SbxisaJtvHIGhWOYJTn+e+WxgLmZ8QQ354B5scn8Z1aAoFZ748yGcO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5pK2OYzwAAAAElI4G2F84AE/jLCpHOABP4ywzEEE0Z8d/FnpNaZSUHVJPI+nrEIGg2QSflx7pPCzquY71ss/hQLEnIXKQ9OnlEP2bdoHU1"

# trigger deploy
